### PR TITLE
Fix related to contacts not specified for addw usage

### LINKED ISSUE #172: Fix addw to make sure correct message is returned
If user does something like 

`addw n/Wedding Name d/12/12/2024 c/`

with nothing after the c/,

The message output is "You can only reference contacts through their index."

Need to change to "Invalid commant format! No contact index is specified"

### PR DESCRIPTION
**Pull request by adipanda2002**
Closes #172

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/ParserUtilTest.java [hunk 1]
```diff
@@ -258,6 +258,13 @@ public void parsePersonIndexString_noDuplicatePersonIndexes_success() throws Exc
         assertEquals(expectedIndexes, actualIndexes);
     }
 
+    @Test
+    public void parsePersonIndexString_emptyPersonIndexString_throwsParseException() {
```
Comment (ignatiusoey09) [inline src/test/java/seedu/address/logic/parser/ParserUtilTest.java:262]: Nice test case!
